name: Build Documents
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install buildtime dependencies
        run: |
          gem install asciidoctor asciidoctor-diagram
          sudo apt-get update
          sudo apt-get install plantuml
      - name: Checkout build branch
        uses: actions/checkout@v2
        with:
          ref: build
          path: build
      - name: Build
        run: |
          make clean
          make -j $(nproc) build/index.html
          rm -rf build/.asciidoctor
      - name: Deploy
        run: |
          cd build
          git config --global user.email "your@email"
          git config --global user.name "Your Name"
          git add -A
          git commit -m "Update Github pages"
          git push
